-- Development seed data for the Student Projects Catalogue.
--
-- Organized in foreign-key dependency order so that every referenced table
-- already has its rows when the referencing INSERT runs.
--
-- All INSERTs are idempotent: ON CONFLICT … DO NOTHING means re-running the
-- script never duplicates rows.  Surrogate-PK tables use OVERRIDING SYSTEM
-- VALUE to fix IDs.
-- TODO(ljezek): Consider resetting the autogenerated sequences by setval.
--
-- Edge cases covered:
--   * Invited student who has not yet accepted (joined_at IS NULL).
--   * Stub project: no description, no technologies, no GitHub URL.
--   * results_unlocked = TRUE (completed) vs FALSE (in-progress).
--   * Submitted vs draft CourseEvaluation (submitted = FALSE).
--   * Team projects with peer feedback and bonus points.
--   * Individual projects without peer feedback.
--   * Course with peer_bonus_budget vs NULL.
--   * Multiple lecturers assigned to a single course.
--
-- Run via: python seed.py [--reset]

-- ============================================================================
-- user
-- ============================================================================
-- 1 admin, 3 lecturers, 6 synthetic past-year students, 15 current students.

INSERT INTO "user" (id, email, github_alias, name, role, created_at)
OVERRIDING SYSTEM VALUE
VALUES
    -- Admin
    (1,  'psi.admin@tul.cz',          'psi-admin',          'PSI Admin',           'ADMIN',    '2025-09-01 10:00:00+00'),
    -- Lecturers
    (2,  'lukas.jezek@tul.cz',         'ljezek',             'Lukáš Ježek',         'LECTURER', '2025-09-01 10:00:00+00'),
    (3,  'roman.spanek@tul.cz',        'roman-spanek',       'Roman Špánek',        'LECTURER', '2025-09-01 10:00:00+00'),
    (4,  'tomas.kral@tul.cz',          'tomaskral',          'Tomáš Král',          'LECTURER', '2025-09-01 10:00:00+00'),
    -- Past students (PSI-2025 and KDP-2025)
    (5,  'alice.novakova@tul.cz',      'alicenov',           'Alice Nováková',      'STUDENT',  '2025-09-15 09:00:00+00'),
    (6,  'bob.krcek@tul.cz',           'bobkrcek',           'Bob Krček',           'STUDENT',  '2025-09-15 09:00:00+00'),
    (7,  'carol.blazkova@tul.cz',      'carolblaz',          'Carol Blažková',      'STUDENT',  '2025-09-15 09:00:00+00'),
    (8,  'dan.horak@tul.cz',           'danhorak',           'Dan Horák',           'STUDENT',  '2025-09-15 09:00:00+00'),
    (9,  'eva.markova@tul.cz',         'evamark',            'Eva Marková',         'STUDENT',  '2025-09-15 09:00:00+00'),
    (10, 'filip.zak@tul.cz',           'filipzak',           'Filip Žák',           'STUDENT',  '2025-09-15 09:00:00+00'),
    -- Current students (PSI-2026, sourced from data/projects.json)
    (11, 'jan.novak@tul.cz',           'jannovak',           'Jan Novák',           'STUDENT',  '2026-02-01 09:00:00+00'),
    (12, 'jana.svobodova@tul.cz',      'janasvo',            'Jana Svobodová',      'STUDENT',  '2026-02-01 09:00:00+00'),
    (13, 'jiri.seps@tul.cz',           'JiriSeps',           'Jiří Šeps',           'STUDENT',  '2026-02-01 09:00:00+00'),
    (14, 'matej.hauschwitz@tul.cz',    'matejhauschwitz',    'Matěj Hauschwitz',    'STUDENT',  '2026-02-01 09:00:00+00'),
    (15, 'vojtech.gero@tul.cz',        'VojtechGero',        'Vojtěch Gerö',        'STUDENT',  '2026-02-01 09:00:00+00'),
    (16, 'martin.cizek@tul.cz',        'cizek-maritn',       'Martin Čížek',        'STUDENT',  '2026-02-01 09:00:00+00'),
    (17, 'jiri.ruta@tul.cz',           'rutaji',             'Jiří Růta',           'STUDENT',  '2026-02-01 09:00:00+00'),
    (18, 'ondrej.braunsveig@tul.cz',   'OndrejBraunsveig',   'Ondřej Braunšveig',   'STUDENT',  '2026-02-01 09:00:00+00'),
    (19, 'david.salek@tul.cz',         'ddeejjvviidd',       'David Šálek',         'STUDENT',  '2026-02-01 09:00:00+00'),
    (20, 'lilian.luca@tul.cz',         'lilianlucatul',      'Lilian Luca',         'STUDENT',  '2026-02-01 09:00:00+00'),
    (21, 'martin.renner@tul.cz',       'martinrenner',       'Martin Renner',       'STUDENT',  '2026-02-01 09:00:00+00'),
    (22, 'zakhar.fedorov@tul.cz',      'zakharfedorov',      'Zakhar Fedorov',      'STUDENT',  '2026-02-01 09:00:00+00'),
    (23, 'vlastimil.palfi@tul.cz',     'PalfiVlastimil',     'Vlastimil Pálfi',     'STUDENT',  '2026-02-01 09:00:00+00'),
    (24, 'jan.reisiegel@tul.cz',       'JanReisiegel',       'Jan Reisiegel',       'STUDENT',  '2026-02-01 09:00:00+00'),
    (25, 'dan.kerslager@tul.cz',       'DanKerslager',       'Dan Keršláger',       'STUDENT',  '2026-02-01 09:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- course
-- ============================================================================
-- PSI: team course with peer bonus.
-- KDP: completed individual course, no peer bonus.

INSERT INTO course (id, code, name, syllabus, term, project_type, min_score,
                    peer_bonus_budget, evaluation_criteria, links,
                    created_by, created_at)
OVERRIDING SYSTEM VALUE
VALUES
    (1, 'PSI', 'Pokročilé Softwarové Inženýrství',
        'Studenti v týmech navrhnou a implementují full-stack softwarový projekt. Důraz je kladen na architekturu, čistý kód, testování, nasazení do produkce, a dokumentaci.',
        'SUMMER', 'TEAM', 40, 10,
        '[{"code":"funkcionalita","description":"Funkčnost aplikace a vhodnost její architektury","max_score":20},{"code":"code_quality","description":"Čistota kódu a kvalita testů (80% coverage, end-to-end testy)","max_score":20},{"code":"nfr","description":"Kvalita NFR: CI/CD, Cloud deployment, monitoring, dokumentace","max_score":20}]'::jsonb,
        '[{"label":"E-learning","url":"https://elearning.tul.cz/course/view.php?id=21545"},{"label":"STAG","url":"https://stag.tul.cz/StagPortletsJSR168/CleanUrl?urlid=prohlizeni-predmet-sylabus&predmetZkrPrac=MTI&predmetZkrPred=PSI&predmetRok=2025&predmetSemestr=LS"},{"label":"GitHub repo with demo","url":"https://github.com/ljezek/tul-psi"}]'::jsonb,
        1, '2025-09-01 12:00:00+00'),
    (2, 'ALD', 'Algoritmizace a datové struktury',
        'Cílem předmětu je seznámit studenty s pokročilejšími datovými strukturami, možnostmi jejich počítačové reprezentace a algoritmy pro jejich zpracování. Nemalá pozornost je věnována práci s grafy (jejich reprezentaci) a algoritmům pro základní grafové úlohy. Z probíraných algoritmů je třeba především zmínit mechanismy pro třídění a vyhledávání v datech..',
        'WINTER', 'INDIVIDUAL', 60, NULL,
        '[{"code":"analysis","description":"Analýza a specifikace požadavků","max_score":30},{"code":"implementation","description":"Implementace a funkčnost","max_score":40},{"code":"report","description":"Technická zpráva","max_score":30}]'::jsonb,
        '[]'::jsonb,
        1, '2025-02-01 12:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- course_lecturer
-- ============================================================================
-- PSI: Lukáš Ježek (2) + Roman Špánek (3).
-- KDP: Tomáš Král (3).

INSERT INTO course_lecturer (course_id, user_id, assigned_at)
VALUES
    (1, 3, '2025-09-01 12:30:00+00'),
    (1, 2, '2025-09-01 12:30:00+00'),
    (2, 4, '2025-02-01 12:30:00+00')
ON CONFLICT (course_id, user_id) DO NOTHING;

-- ============================================================================
-- project
-- ============================================================================
-- PSI-2025 (ids 1–3): fully completed, results_unlocked = TRUE.
-- PSI-2026 (ids 4–8): in-progress, results_unlocked = FALSE.
--   id 4 — fully populated (description, GitHub, live_url, technologies set).
--   id 5 — partial: GitHub set but no description or technologies yet.
--   id 6 — stub:    only title seeded; owner has not linked a repo yet.
--   id 7, 8 — normal in-progress: description and GitHub set, no live_url.
-- KDP-2025 (ids 9–10): fully completed, results_unlocked = TRUE.

INSERT INTO project (id, title, description, github_url, live_url, technologies,
                     results_unlocked, course_id, academic_year, created_at)
OVERRIDING SYSTEM VALUE
VALUES
    -- PSI-2025 completed projects
    (1,  'TUL Event Planner',
         'Webová aplikace pro správu a přihlašování na fakultní akce a workshopy.',
         'https://github.com/PSI-2025/event-planner',
         'https://event-planner.tul.cz',
         '["Python","FastAPI","React","PostgreSQL"]'::jsonb,
         true, 1, 2025, '2025-09-20 10:00:00+00'),
    (2,  'Studijní Asistent',
         'Chatbot integrovaný s Moodle pro zodpovídání dotazů ke studijním materiálům.',
         'https://github.com/PSI-2025/studijni-asistent',
         NULL,
         '["Python","LangChain","Vue.js"]'::jsonb,
         true, 1, 2025, '2025-09-20 10:00:00+00'),
    (3,  'Budget Tracker',
         'Mobilní aplikace pro sledování osobních výdajů s exportem do CSV.',
         'https://github.com/PSI-2025/budget-tracker',
         'https://budget.tul.cz',
         '["Flutter","Dart","Firebase"]'::jsonb,
         true, 1, 2025, '2025-09-20 10:00:00+00'),
    -- PSI-2026 in-progress projects (sourced from data/projects.json)
    (4,  'Lectors - Student Projects Catalogue',
         'Plná implementace Student Projects Catalogue — React SPA + FastAPI backend + PostgreSQL.',
         'https://github.com/ljezek/tul-psi',
         'https://psi.tul.cz',
         '["React","TypeScript","FastAPI","Python","PostgreSQL","Docker"]'::jsonb,
         false, 1, 2026, '2026-02-15 10:00:00+00'),
    (5,  'Bookstore',
         NULL,
         'https://github.com/matejhauschwitz/PSI',
         NULL,
         '[]'::jsonb,
         false, 1, 2026, '2026-02-15 10:00:00+00'),
    (6,  'LOL tracker',
         NULL,
         NULL,
         NULL,
         '[]'::jsonb,
         false, 1, 2026, '2026-02-15 10:00:00+00'),
    (7,  'PSI - Kanban Board',
         'Webová aplikace: PSI - Kanban Board.',
         'https://github.com/martinrenner/PSI',
         NULL,
         '["Python","React"]'::jsonb,
         false, 1, 2026, '2026-02-15 10:00:00+00'),
    (8,  'QuizApp',
         'Webová aplikace: QuizApp.',
         'https://github.com/PSI-RDB-2026/QuizApp',
         NULL,
         '["Python","React"]'::jsonb,
         false, 1, 2026, '2026-02-15 10:00:00+00'),
    -- KDP-2025 completed individual projects
    (9,  'Analýza výkonnosti distribuovaných systémů',
         'Srovnání latence a propustnosti různých message-broker architektur.',
         'https://github.com/alicenov/kdp-2025',
         NULL,
         '["Python","RabbitMQ","Kafka"]'::jsonb,
         true, 2, 2025, '2025-02-15 10:00:00+00'),
    (10, 'Detekce anomálií v IoT datech pomocí ML',
         'Klasifikace chybových stavů senzorů pomocí izolačního lesa.',
         'https://github.com/danhorak/kdp-2025',
         NULL,
         '["Python","scikit-learn","MQTT"]'::jsonb,
         true, 2, 2025, '2025-02-15 10:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- project_member
-- ============================================================================
-- invited_by = NULL means the student was seeded directly as the project owner.
-- joined_at  = NULL means the invitation has not been accepted yet (edge case).

INSERT INTO project_member (id, project_id, user_id, invited_by, invited_at, joined_at)
OVERRIDING SYSTEM VALUE
VALUES
    -- PSI-2025 project 1 (TUL Event Planner): Alice (owner) + Bob
    (1,  1,  5,  NULL, '2025-09-20 10:00:00+00', '2025-09-20 10:00:00+00'),
    (2,  1,  6,  5,    '2025-09-20 10:05:00+00', '2025-09-20 10:10:00+00'),
    -- PSI-2025 project 2 (Studijní Asistent): Carol (owner) + Dan + Eva
    (3,  2,  7,  NULL, '2025-09-20 10:00:00+00', '2025-09-20 10:00:00+00'),
    (4,  2,  8,  7,    '2025-09-20 10:05:00+00', '2025-09-20 10:10:00+00'),
    (5,  2,  9,  7,    '2025-09-20 10:05:00+00', '2025-09-20 10:10:00+00'),
    -- PSI-2025 project 3 (Budget Tracker): Filip (owner) + Bob
    (6,  3,  10, NULL, '2025-09-20 10:00:00+00', '2025-09-20 10:00:00+00'),
    (7,  3,  6,  10,   '2025-09-20 10:05:00+00', '2025-09-20 10:10:00+00'),
    -- PSI-2026 project 4 (Lectors SPC): Lukáš (owner) + Roman
    (8,  4,  11, NULL, '2026-02-15 10:00:00+00', '2026-02-15 10:00:00+00'),
    (9,  4,  12, 11,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    -- PSI-2026 project 5 (Bookstore): Jiří Šeps (owner) + Matěj + Vojtěch
    (10, 5,  13, NULL, '2026-02-15 10:00:00+00', '2026-02-15 10:00:00+00'),
    (11, 5,  14, 13,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    (12, 5,  15, 13,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    -- PSI-2026 project 6 (LOL tracker — stub): Martin Čížek (owner) + Jiří Růta (invited, NOT joined) + Ondřej
    (13, 6,  16, NULL, '2026-02-15 10:00:00+00', '2026-02-15 10:00:00+00'),
    (14, 6,  17, 16,   '2026-02-15 10:05:00+00', NULL),
    (15, 6,  18, 16,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    -- PSI-2026 project 7 (PSI Kanban Board): David (owner) + Lilian + Martin Renner + Zakhar
    (16, 7,  19, NULL, '2026-02-15 10:00:00+00', '2026-02-15 10:00:00+00'),
    (17, 7,  20, 19,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    (18, 7,  21, 19,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    (19, 7,  22, 19,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    -- PSI-2026 project 8 (QuizApp): Vlastimil (owner) + Jan Reisiegel + Dan Keršláger
    (20, 8,  23, NULL, '2026-02-15 10:00:00+00', '2026-02-15 10:00:00+00'),
    (21, 8,  24, 23,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    (22, 8,  25, 23,   '2026-02-15 10:05:00+00', '2026-02-15 10:10:00+00'),
    -- KDP-2025 project 9 (Analýza výkonnosti): Alice
    (23, 9,  5,  NULL, '2025-02-15 10:00:00+00', '2025-02-15 10:00:00+00'),
    -- KDP-2025 project 10 (Detekce anomálií): Dan
    (24, 10, 8,  NULL, '2025-02-15 10:00:00+00', '2025-02-15 10:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- project_evaluation
-- ============================================================================
-- PSI-2025: both lecturers (Lukáš Ježek id=2, Roman Špánek id=3) evaluate
--           all three projects.  Ježek awards 16/20 per criterion; Špánek
--           awards 18/20 per criterion.
-- KDP-2025: Jan Král evaluates both projects, awarding 25 per criterion.

INSERT INTO project_evaluation (project_id, lecturer_id, scores, submitted, updated_at)
VALUES
    -- Project 1 — Lukáš Ježek
    (1, 2, '[{"criterion_code":"funkcionalita","score":18,"strengths":"Skvělé UI a rychlá odezva.","improvements":"Občas pomalejší API při větším zatížení."},{"criterion_code":"code_quality","score":19,"strengths":"Velmi čistý kód a dobrá struktura.","improvements":"Chybí pár docstrings u helper funkcí."},{"criterion_code":"nfr","score":17,"strengths":"Nasazení na jedničku.","improvements":"Doporučuji přidat lepší monitoring."}]'::jsonb,
     true, '2026-01-15 10:00:00+00'),
    -- Project 1 — Roman Špánek
    (1, 3, '[{"criterion_code":"funkcionalita","score":17,"strengths":"Z pohledu uživatele super.","improvements":"Architektura by snesla menší refaktoring pro lepší škálovatelnost."},{"criterion_code":"code_quality","score":20,"strengths":"Ukázkové testy a pokrytí.","improvements":"Nemám co vytknout."},{"criterion_code":"nfr","score":16,"strengths":"Základní CI/CD funguje.","improvements":"Deployment by se dal více zautomatizovat."}]'::jsonb,
     true, '2026-01-15 10:00:00+00'),
    -- Project 2 — Lukáš Ježek
    (2, 2, '[{"criterion_code":"funkcionalita","score":15,"strengths":"Nápad je skvělý a inovativní.","improvements":"Aplikace občas padá při edge cases."},{"criterion_code":"code_quality","score":14,"strengths":"Kód je celkem čitelný.","improvements":"Velmi slabé pokrytí testy."},{"criterion_code":"nfr","score":15,"strengths":"Dobrá dokumentace API.","improvements":"Chybí automatický deployment pipeline."}]'::jsonb,
     true, '2026-01-15 10:00:00+00'),
    -- Project 2 —  Roman Špánek
    (2, 3, '[{"criterion_code":"funkcionalita","score":14,"strengths":"Základní use-cases fungují dobře.","improvements":"Složitější scénáře nebyly plně otestovány."},{"criterion_code":"code_quality","score":16,"strengths":"Snaha o čistou architekturu.","improvements":"Místy příliš složité abstrakce."},{"criterion_code":"nfr","score":14,"strengths":"Aplikace běží v cloudu.","improvements":"Logování chyb by mohlo být podstatně lepší."}]'::jsonb,
     true, '2026-01-15 10:00:00+00'),
    -- Project 3 — Lukáš Ježek
    (3, 2, '[{"criterion_code":"funkcionalita","score":20,"strengths":"Vše funguje bezchybně, výborná architektura.","improvements":"Žádné podstatné vady."},{"criterion_code":"code_quality","score":18,"strengths":"Solidní kód.","improvements":"Drobné prohřešky proti jmenným konvencím."},{"criterion_code":"nfr","score":19,"strengths":"Perfektní dokumentace a deployment.","improvements":"Chybí load testing."}]'::jsonb,
     true, '2026-01-15 10:00:00+00'),
    -- Project 3 —  Roman Špánek
    (3, 3, '[{"criterion_code":"funkcionalita","score":19,"strengths":"Skvělá práce, robustní řešení.","improvements":"Některé formuláře by mohly mít lepší validaci."},{"criterion_code":"code_quality","score":19,"strengths":"Velmi dobré testy.","improvements":"Zbytečně velký počet závislostí."},{"criterion_code":"nfr","score":20,"strengths":"Excelentní NFR a zabezpečení.","improvements":"Vše v pořádku."}]'::jsonb,
     true, '2026-01-15 10:00:00+00'),
    -- KDP project 9 — Jan Král
    (9,  3, '[{"criterion_code":"analysis","score":28,"strengths":"Velmi podrobná a pečlivá analýza.","improvements":"Uvítal bych více grafů pro vizualizaci."},{"criterion_code":"implementation","score":35,"strengths":"Funkční a výkonný prototyp.","improvements":"Občasné bugy v edge cases při vysoké zátěži."},{"criterion_code":"report","score":29,"strengths":"Výborně napsaný text.","improvements":"Drobné překlepy v závěru."}]'::jsonb,
     true, '2026-01-10 10:00:00+00'),
    -- KDP project 10 — Jan Král
    (10, 3, '[{"criterion_code":"analysis","score":25,"strengths":"Základní analýza je dostatečná.","improvements":"Chybí srovnání s existujícími řešeními."},{"criterion_code":"implementation","score":38,"strengths":"Velmi robustní řešení s izolací anomálií.","improvements":"Vyšší spotřeba paměti u rozsáhlejších datasetů."},{"criterion_code":"report","score":27,"strengths":"Zpráva je přehledná.","improvements":"Chybí hlubší zhodnocení budoucího rozvoje."}]'::jsonb,
     true, '2026-01-10 10:00:00+00')
ON CONFLICT (project_id, lecturer_id) DO NOTHING;

-- ============================================================================
-- course_evaluation
-- ============================================================================
-- PSI-2025 (ids 1–7): all submitted, rating = 4.
-- KDP-2025 (ids 8–9): all submitted, rating = 5.
-- PSI-2026 (id 10):   draft (submitted = FALSE, strengths/improvements NULL).

INSERT INTO course_evaluation (id, project_id, student_id, rating,
                                strengths, improvements, submitted, updated_at)
OVERRIDING SYSTEM VALUE
VALUES
    -- PSI-2025 project 1 (TUL Event Planner): Alice + Bob
    (1,  1,  5,  5, 'Projekt mě velmi bavil a naučil jsem se hodně o Reactu.', 'Možná by se hodil jeden úvodní tutoriál na FastAPI navíc.', true,  '2026-01-20 10:00:00+00'),
    (2,  1,  6,  4, 'Skvělá týmová práce a podpora cvičících.', 'Někdy byly požadavky v zadání příliš obecné.', true,  '2026-01-20 10:00:00+00'),
    -- PSI-2025 project 2 (Studijní Asistent): Carol + Dan + Eva
    (3,  2,  7,  3, 'Zajímavé téma, ale hodně času zabralo samostudium technologií.', 'Přednášky mohly být více propojené s praxí.', true,  '2026-01-20 10:00:00+00'),
    (4,  2,  8,  5, 'Výborný předmět, ideální příprava na praxi.', 'Nemám co vytknout, vše fungovalo skvěle.', true,  '2026-01-20 10:00:00+00'),
    (5,  2,  9,  4, 'Líbila se mi volnost při výběru technologií.', 'Hodnocení mohlo být transparentnější už od začátku semestru.', true,  '2026-01-20 10:00:00+00'),
    -- PSI-2025 project 3 (Budget Tracker): Filip + Bob
    (6,  3,  10, 5, 'Super předmět, oceňuji důraz na NFR a CI/CD.', 'Zpočátku jsem bojoval s Dockerem, nějaký tahák by se hodil.', true,  '2026-01-20 10:00:00+00'),
    (7,  3,  6,  4, 'Konzultace s cvičícími byly velmi přínosné.', 'Uvítal bych více termínů pro průběžné odevzdání.', true,  '2026-01-20 10:00:00+00'),
    -- KDP-2025 project 9 (Analýza výkonnosti): Alice
    (8,  9,  5,  4, 'Práce na projektu mi dala skvělou přípravu na obhajobu.',       'Více konzultačních termínů by pomohlo v průběhu zpracování.',       true,  '2026-01-20 10:00:00+00'),
    -- KDP-2025 project 10 (Detekce anomálií): Dan
    (9,  10, 8,  5, 'Velmi zajímavé téma, které jsem si mohl zvolit sám.', 'Občas zdlouhavé čekání na feedback ke specifikaci.', true,  '2026-01-20 10:00:00+00'),
    -- PSI-2026 project 4 (Lectors SPC): Lukáš — draft, free-text not yet filled in
    (10, 4,  11, 4, NULL, NULL, false, '2026-03-01 09:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- peer_feedback
-- ============================================================================
-- Only PSI-2025 projects have peer feedback (peer_bonus_budget = 10).
-- Each team member distributes 10 points evenly across their teammates.
--   2-person team: each teammate receives 10 bonus points.
--   3-person team: each teammate receives 5 bonus points.

INSERT INTO peer_feedback (course_evaluation_id, receiving_student_id,
                            strengths, improvements, bonus_points)
VALUES
    -- CE 1 (Alice evaluates project 1): feedback for Bob (id 6)
    (1,  6,  'Výborná orientace v backendu, pomohl mi s databází.', 'Občas by mohl rychleji odpovídat na Slacku.', 10),
    -- CE 2 (Bob evaluates project 1): feedback for Alice (id 5)
    (2,  5,  'Skvělá organizátorka, hlídala všechny termíny.', 'Méně se zapojovala do složitější logiky v kódu.', 10),
    -- CE 3 (Carol evaluates project 2): feedback for Dan (id 8) + Eva (id 9)
    (3,  8,  'Kód od něj byl vždy čistý a bez chyb.', 'Mohl by lépe dokumentovat své pull requesty.',  5),
    (3,  9,  'Vymyslela skvělý design a frontend.', 'Někdy se zasekávala na detailech místo postupu.',  5),
    -- CE 4 (Dan evaluates project 2): feedback for Carol (id 7) + Eva (id 9)
    (4,  7,  'Spolehlivá, vyřešila spoustu složitých problémů.', 'Trochu chaotické slučování větví v Gitu.',  5),
    (4,  9,  'Super práce na prezentaci a dokumentaci.', 'Méně technického přínosu oproti ostatním.',  5),
    -- CE 5 (Eva evaluates project 2): feedback for Carol (id 7) + Dan (id 8)
    (5,  7,  'Přátelská a proaktivní komunikace.', 'Příště by mohla víc delegovat úkoly.',  5),
    (5,  8,  'Absolutní technický expert našeho týmu.', 'Trochu víc trpělivosti při vysvětlování kódu ostatním.',  5),
    -- CE 6 (Filip evaluates project 3): feedback for Bob (id 6)
    (6,  6,  'Vždy přišel s kreativním řešením problému.', 'Zbytečně často refaktoroval fungující kód.', 10),
    -- CE 7 (Bob evaluates project 3): feedback for Filip (id 10)
    (7,  10, 'Dobře nastavil architekturu od samého začátku.', 'Dělal příliš velké commity, špatně se to revidovalo.', 10)
ON CONFLICT (course_evaluation_id, receiving_student_id) DO NOTHING;