receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]

processors:
  batch:
  resourcedetection:
    detectors: [env]

exporters:
  # Traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Metrics
  prometheus:
    endpoint: 0.0.0.0:8889

  # Logs (optional: send to stdout for debugging)
  debug:
    verbosity: basic

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp/jaeger, debug]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [prometheus, debug]
